### ISSUE TITLE
Feature request: Show who's locking

### ISSUE THREAD

**Issue by raimi** [workflo/shaback#12]
Our "shaback gc" sometimes shows: Cannot exclusively lock repository while other locks exist. Check lock files in /...

Please show the other lock-Files (simple list) so that the cron output contains the offending machin(s) and/or problems.

Thanks, I just loooove shaback :)

**Comment by raimi** [comment]
Beep. Still relevant :)

**Comment by workflo** [comment]
Jetzt bekommt man so eine Meldung, wenn das Locking nicht klappt:

`Repository is locked exclusively. Check lock files in /Users/wolff/tmp/shaback/locks:
noname-17.lock; noname-1727.lock`
