### ISSUE TITLE
Feature-Wunsch: Auto-Load einer .lua-Datei aus Repo

### ISSUE THREAD

**Issue by raimi** [workflo/shaback#13]
Vorschlag: <repo>/repo.lua wird geladen, sobald das repo bekannt ist, so das sich als Ladereihenfolge ergibt:

- globale defaults (/etc/...)
- repo-defaults (repo.lua)
- lokale defaults (~/.shaback.lua)
- Kommandozeile

das finde ich sinnvoll und gibt mir die moeglichkeit "das repo" zu konfigurieren.

**Comment by workflo** [comment]
Die Ladereihenfolge geht so leider regelmäßig nicht, weil meist erst in ~/.shaback.lua oder gar erst in der Commandline steht, wo das Repo ist.

repo.lua könnte man also immer erst ganz am Schluss laden. Hilft dir das trotzdem?

**Comment by workflo** [comment]
OK, dann wird repo/repo.lua also als letztes geladen...

**Comment by raimi** [comment]
Siehe Code-Kommentar
