### ISSUE TITLE
Feature-Wunsch: Sowas wie os.execute() am Ende

### ISSUE THREAD

**Issue by raimi** [workflo/shaback#14]
Fuer das os.execute() haette ich gern ein Gegenstueck am Ende, um das Repo wieder zu umounten.

os.executeAtEnd() oder osAfter.execute() - mir egal. Hauptsache es zieht an der Stelle, an der auch das lock-File geloescht wird (ctrl-c-fall).

**Comment by workflo** [comment]
Kompliziert und wir brauchen es jetzt doch nicht.
