### ISSUE TITLE
Feature Request: Maintenance of *.sroot-History

### ISSUE THREAD

**Issue by raimi** [workflo/shaback#16]
* shaback history --keep 3
Remove all but the last 3 of each entry point. (Or even: --keep 3d / --keep 3w - keep only 3 days or 3 weeks worth of backup entries points?)

* shaback history list
Show the entry points and how much history there is, each in one line.

backup name, history, newest, oldest
foo, 3, 2016-06-05-..., 2016-01-01-...

**Comment by raimi** [comment]
some more ideas

* shaback history
show the list of backup names currently in store
* shaback history --newest
show the all the newest *.sroot filenames 
* shaback history --newest backupname
show the newest sroot filename of the given backup name - use it to automatically recover the last one?

**Comment by workflo** [comment]
See [Housekeeping](https://github.com/workflo/shaback/wiki/Housekeeping)

**Comment by workflo** [comment]
See master branch. Good enough?
