### ISSUE TITLE
~/.shaback-read-cache.gdbm vs. multiple repos / backup sets / concurrency

### ISSUE THREAD

**Issue by raimi** [workflo/shaback#6]
Update: OK, my bad. I misunderstood what this cache file is being used for.

It's only caching reading of tree-files, which actually is a global property.

Remaining problem: Concurrent access to this file when one user runs multiple shaback instances (no matter which repo or backup set).

---8<---

While experimenting with different Repo formats and Backup sets, it occured to me: The ~/.shaback-read-cache.gdbm must not be user-global. With the use of various Config files it is perfectly legal for a user to have several repos and backup sets.

A shared global instance of the above cache yields wrong results.

Options to fix:
- Derive file name from repo name
- Explicitly make it part of the config file
- Help user by sanity-checking if cache file belongs to current repo (UUIDs of Repos?)

**Comment by workflo** [comment]
A UUID derived from the local repo path should do the trick.
This UUID could become part of the filename like in: `~/.shaback-cache-7a7e72943f4b383363b228737ef9c.gdbm`

**Comment by workflo** [comment]
Obsolete: _read cache_ is no longer needed.
